- name: Setup Minecraft Server
  hosts: minecraft
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Create Minecraft directory
      file:
        path: /home/ubuntu/minecraft
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Download Minecraft server JAR
      become_user: ubuntu
      get_url:
        url: https://piston-data.mojang.com/v1/objects/e6ec2f64e6080b9b5d9b471b291c33cc7f509733/server.jar
        dest: /home/ubuntu/minecraft/minecraft_server.jar

    - name: Accept EULA
      copy:
        dest: /home/ubuntu/minecraft/eula.txt
        content: "eula=true\n"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Create systemd service
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory=/home/ubuntu/minecraft
          ExecStart=/usr/bin/java -Xmx2G -Xms1G -jar minecraft_server.jar nogui
          ExecStop=/bin/kill -SIGINT $MAINPID
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start Minecraft service
      systemd:
        name: minecraft
        enabled: yes
        state: started
